### ISSUE TITLE
Encoding error in localized terminal

### ISSUE THREAD

**Issue by terokinnunen** [wgwoods/fedup#63]
Fedup update failed when run with localized terminal LANG=fi_FI.UTF-8. 

Fedup version:
fedup-0.9.2-1.fc21.noarch

Command:
sudo fedup --network 22

Tail of output:

```
warning: /var/cache/system-upgrade/rpmfusion-nonfree/packages/dropbox-2.10.0-2.fc22.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID a6708da3: NOKEY
Importing GPG key 0xA6708DA3:
 Userid     : "RPM Fusion nonfree repository for Fedora (22) <rpmfusion-buildsys@lists.rpmfusion.org>"
 Fingerprint: bad2 40a4 79ff 87e7 791e 105f 27d7 7a09 a670 8da3
 Package    : rpmfusion-nonfree-release-21-1.noarch (@/rpmfusion-nonfree-release-21.noarch/21)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-22
Traceback (most recent call last):
  File "/bin/fedup", line 291, in <module>
    main(args)
  File "/bin/fedup", line 201, in main
    pkgs = download_packages(f, add_install=args.add_install)
  File "/bin/fedup", line 85, in download_packages
    f.download_packages(updates, callback=output.DownloadCallback())
  File "/usr/lib/python2.7/site-packages/fedup/download.py", line 358, in download_packages
    self._checkSignatures(updates, callback)
  File "/usr/lib/python2.7/site-packages/fedup/download.py", line 495, in _checkSignatures
    self.getKeyForPackage(po, fullaskcb=keycheck)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 6192, in getKeyForPackage
    "timestamp": info['timestamp']})
  File "/usr/lib/python2.7/site-packages/fedup/download.py", line 494, in <lambda>
    keycheck = lambda info: self._GPGKeyCheck(info, callback)
  File "/usr/lib/python2.7/site-packages/fedup/download.py", line 513, in _GPGKeyCheck
    return callback.userconfirm()
  File "/usr/lib/python2.7/site-packages/fedup/textoutput.py", line 136, in userconfirm
    return YumOutput().userconfirm()
  File "/usr/share/yum-cli/output.py", line 980, in userconfirm
    choice = raw_input(prompt)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 6: ordinal not in range(128)
```

Workaround:
Run command

```
  export LANG=en
```

before fedup command.

**Comment by terokinnunen** [comment]
This is likely the same prompt with yum update command. Yum does not choke at this prompt:

```
Yhteensä                                           1.2 MB/s | 552 MB  07:46     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-21
Importing GPG key 0xA668B376:
 Userid     : "RPM Fusion nonfree repository for Fedora (21) <rpmfusion-buildsys@lists.rpmfusion.org>"
 Fingerprint: e160 058e f06f a4c3 c15d 0f86 0174 46d1 a668 b376
 Package    : rpmfusion-nonfree-release-21-1.noarch (@/rpmfusion-nonfree-release-21.noarch)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-21
Onko tämä ok [k/E]: k
```

yum-3.4.3-153.fc21.noarch
